---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 80
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- dist/
- test/
